-- TASK 7: EMPLOYEE SALARY MANAGEMENT
-- CREATE TABLE TB_EMP_SALARY

CREATE TABLE TB_EMP_SALARY (
  EMP_ID CHAR(5) NOT NULL,
  EMP_NAME VARCHAR(30),
  DEPT_CODE CHAR(3),
  SALARY DECIMAL(9,2),
  PRIMARY KEY(EMP_ID)
) IN DATABASE Z73460;
