-- TASK 19: CUSTOMER IMPORT SYSTEM
-- CREATE TABLE TB_CUSTOMERS

CREATE TABLE TB_CUSTOMERS (
  CUST_ID CHAR(6) NOT NULL,  
  CUST_NAME VARCHAR(30),    
  EMAIL VARCHAR(40),      
  PHONE CHAR(10),  
  CREDIT_LIMIT DECIMAL(9,2),    
  PRIMARY KEY (CUST_ID) 
) IN DATABASE Z73460;        
