-- TASK 24: BALANCE RECONCILIATION
-- CREATE TABLE TB_ACCOUNTS

CREATE TABLE TB_ACCOUNTS (       
    ACCOUNT_ID CHAR(6) NOT NULL,  
    BALANCE    DECIMAL (11,2),    
    LAST_UPDATE TIMESTAMP,        
    PRIMARY KEY (ACCOUNT_ID)      
 ) IN DATABASE Z73460;         
