INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000001','JOHN SMITH','NE','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000002','MARY JOHNSON','NE','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000003','ROBERT WILLIAMS','NE','C','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000004','PATRICIA BROWN','NE','R','I');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000005','MICHAEL JONES','NE','C','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000006','LINDA GARCIA','NE','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000007','WILLIAM MILLER','NE','C','I');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000008','ELIZABETH DAVIS','NE','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000009','DAVID RODRIQUEZ','NE','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000010','BARBARA MARTINEZ','NE','C','A');                    
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000011','DAVID RODRIQUEZ','NE','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000012','JENNIFER LOPEZ','SW','C','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000013','CHARLES GONZALEZ','SW','R','I');                    
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000014','SUSAN WILSON','SW','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000015','JOSEPH ANDERSON','SW','C','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000016','JESSICA THOMAS','SW','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000017','THOMAS TAYLOR','SW','C','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000018','SARAH MOORE','SW','R','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000019','CHRISTOPHER JACKSON','SW','R','A');                 
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000020','KAREN MARTIN','SW','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000021','DANIEL LEE','EU','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000022','NANCY PEREZ','EU','C','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000023','PAUL THOMPSON','EU','R','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000024','LISA WHITE','EU','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000025','MARK HARRIS','EU','C','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000026','SANDRA SANCHEZ','EU','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000027','DONALD CLARK','EU','C','I');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000028','ASHLEY RAMIREZ','EU','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000029','STEVEN LEWIS','EU','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000030','BETTY ROBINSON','EU','C','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000031','ANDREW WALKER','AS','R','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000032','DOROTHY YOUNG','AS','C','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000033','JOSHUA ALLEN','AS','R','I');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000034','MARGARET KING','AS','R','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000035','KEVIN WRIGHT','AS','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000036','SHARON SCOTT','AS','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000037','BRIAN TORRES','AS','C','I');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000038','MICHELLE NGUYEN','AS','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000039','GEORGE HILL','AS','R','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000040','EMILY FLORES','AS','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000041','EDWARD GREEN','NE','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000042','AMY ADAMS','NE','C','A');                           
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000043','RONALD NELSON','NE','R','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000044','ANGELA BAKER','NE','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000045','KENNETH HALL','NE','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000046','REBECCA RIVERA','NE','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000047','JASON CAMPBELL','NE','C','I');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000048','STEPHANIE MITCHELL','NE','R','A');                  
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000049','SCOTT CARTER','NE','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000050','LAURA ROBERTS','NE','C','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000051','ERIC GOMEZ','SW','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000052','CYNTHIA PHILLIPS','SW','C','A');                    
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000053','GARY EVANS','SW','R','I');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000054','KATHLEEN TURNER','SW','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000055','RYAN DIAZ','SW','C','A');                           
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000056','DEBORAH PARKER','SW','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000057','NICHOLAS CRUZ','SW','C','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000058','CHRISTINE EDWARDS','SW','R','A');                   
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000059','STEPHEN COLLINS','SW','R','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000060','RUTH STEWART','SW','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000061','PATRICK MORRIS','EU','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000062','ANNA ROGERS','EU','C','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000063','DENNIS REED','EU','R','I');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000064','DIANE COOK','EU','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000065','GREGORY MORGAN','EU','C','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000066','CAROL BELL','EU','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000067','FRANK MURPHY','EU','C','I');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000068','HEATHER BAILEY','EU','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000069','PETER RIVAS','EU','R','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000070','JULIA COOPER','EU','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000071','DOUGLAS RICHARDSON','AS','R','A');                  
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000072','VICTORIA COX','AS','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000073','RUSSELL HOWARD','AS','R','I');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000074','KELLY WARD','AS','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000075','ADAM PETERSON','AS','C','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000076','MEGAN GRAY','AS','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000077','CRAIG JAMES','AS','C','I');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000078','MELISSA WATSON','AS','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000079','AARON BROOKS','AS','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000080','RACHEL KELLY','AS','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000081','SHAWN SANDERS','NE','R','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000082','TERESA PRICE','NE','C','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000083','LARRY BENNETT','NE','R','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000084','JANET WOOD','NE','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000085','PHILLIP BARNES','NE','C','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000086','DIANA ROSS','NE','R','A');                          
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000087','CARL HENDERSON','NE','C','I');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000088','MONICA COLEMAN','NE','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000089','BILLY JENKINS','NE','R','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000090','KATHERINE PERRY','NE','C','A');                     
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000091','TODD POWELL','SW','R','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000092','ALICIA LONG','SW','C','A');                         
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000093','ARTHUR PATTERSON','SW','R','I');                    
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000094','JOYCE HUGHES','SW','R','A');                        
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000095','VICTOR FLORES','SW','C','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000096','PAULA WASHINGTON','SW','R','A');                    
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000097','JEREMY BUTLER','SW','C','I');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000098','GLORIA SIMMONS','SW','R','A');                      
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000099','HAROLD FOSTER','SW','R','A');                       
INSERT INTO T_CUSTOMER (CUST_ID, CUST_NAME, REGION, SEGMENT, STATUS)  
VALUES ('000100','TIFFANY GONZALES','SW','C','A');                    
