-- TASK 21: ORDERS WITH PRODUCT VALIDATION
-- CREATE TABLE TB_PRODUCTS

CREATE TABLE TB_PRODUCTS (          
   PROD_ID       CHAR(5) NOT NULL,  
   PROD_NAME     VARCHAR(30),       
   UNIT_PRICE    DECIMAL(7, 2),     
   STOCK_QTY     INTEGER,           
   PRIMARY KEY (PROD_ID)            
) IN DATABASE Z73460;               
