-- TASK 29: OPERATION LOG RECONCILIATION 
-- CREATE TB_ACCOUNT_BAL

CREATE TABLE TB_ACCOUNT_BAL (     
   ACCT_ID CHAR(6) NOT NULL,      
   BALANCE DECIMAL(11,2),         
   LAST_DATE DATE,                
   PRIMARY KEY(ACCT_ID)           
) IN DATABASE Z73460;             
