-- TASK 25: PRICE UPDATE SYSTEM
-- CREATE TB_PRICE_HISTORY

CREATE TABLE TB_PRICE_HISTORY (          
  PROD_ID CHAR(5) NOT NULL,              
  OLD_PRICE DECIMAL(7,2),                
  NEW_PRICE DECIMAL(7,2),                
  CHANGE_DATE DATE NOT NULL WITH DEFAULT,
  PRIMARY KEY (PROD_ID,CHANGE_DATE)      
) IN DATABASE Z73460;                    
