-- TASK 8: CALCULATION OF EMPLOYEE BONUSES
-- CREATE TABLE TB_SALES_BONUS

CREATE TABLE TB_SALES_BONUS (
  EMP_ID CHAR(6) NOT NULL,   
  EMP_NAME VARCHAR(30),      
  REGION_CODE CHAR(2),       
  YEAR_SALES DECIMAL(11,2),  
  BONUS_AMT DECIMAL(9,2),    
  PRIMARY KEY (EMP_ID)       
) IN DATABASE Z73460;        
