-- TASK 20: 
-- CREATE TABLE TB_EMPLOYEES

CREATE TABLE TB_EMPLOYEES (
  EMP_ID        CHAR(5) NOT NULL,
  EMP_NAME      VARCHAR(30),
  DEPT          CHAR(3),    
  SALARY        DECIMAL(9, 2),  
  HIRE_DATE     DATE,
  STATUS        CHAR(1), 
  PRIMARY KEY (EMP_ID)
) IN DATABASE Z73460;        
